language: python
matrix:
    include:
        python:
          - "3.5"
          - "3.6"
          - "3.7"
        dist: xenial
cache: pip
install:
  - python setup.py install
script:
  - python setup.py pytest
